### ISSUE TITLE
Speech recognition does not work with Adobe Videoconference software open on the same browser / computer

### ISSUE THREAD

**Issue by sergutsan** [fernandezgom/it2l-platform#64]
Steps to reproduce:
1. Open a telco on https://webconf.vc.dfn.de/
2. Open iTalk2Learn

What is the intended outcome: 
iTalk2Learn listens to the student and recognises what is said

What is the actual outcome: 
It does not hear anything apparently.

**Comment by fernandezgom** [comment]
Importan to have mention do not testing while the micro is opened on a telco meeting
