### ISSUE TITLE
Resizing problems

### ISSUE THREAD

**Issue by sergutsan** [fernandezgom/it2l-platform#75]
Reported by Junaid.

How to reproduce the problem: 
1. Start it2l. Go to a FL problem. 
2. Resize the window. 

What should happen?
The system works as normal, more or less. 

What happens instead?
FL continues working but the rest of it2l is not accessible (e.g. cannot go next, etc)

Browser: Firefox 38 on Win7

**Comment by sergutsan** [comment]
Is this fixed?

**Comment by fernandezgom** [comment]
Forgot this. I will ask Testaluna tomorrow because they developed a popup that creates this problem. In the meantime I will to try to solve by my side.

**Comment by mavrikis** [comment]
Testaluna is closed. Weren't new stylesheets supposed to resolve this?

Sometimes students resize just to be playful and in full screen this
happens more often when you take the mouse on the address bar, as we saw
last time.

Not crucial given that a refresh fixes it but not ideal situation either.

**Comment by fernandezgom** [comment]
I found the solution, but I cannot apply to it2l-2 from here.

In the resize property from the TL popup there is a property called display which is setted to block when it should be to none.
