### ISSUE TITLE
Speech-reco instance monitor

### ISSUE THREAD

**Issue by sergutsan** [fernandezgom/it2l-platform#77]
I think this is important to run the system in the classroom: we need a monitor for the speech-reco engines. This monitor should provide the following information to an admin (e.g. Jose,
Hamza, even Claudia with a bit of training):

- Which instances are working and which are idle
- Which student is using each of the working instances

Example of possible command-like interface: 

    sergut@bbk-705$ ssh it2l-2.dcs.bbk.ac.uk 
    Pasword: 
    sergut@it2l-2$ it2l-speech-reco-monitor
    Welcome to iTalk2Learn's Speech Recognition Monitor. 
    Checking whether there is an iTalk2Learn server running on this machine... OK
    > ls
    There are 4 speech-reco instances working (out of 30)
    Instance 2 is used by user 'student3'
    Instance 4 is used by user 'student5'
    Instance 22 is used by user 'student1'
    Instance 23 is used by user 'mavrikis' 
    > exit
    sergut@it2l-2$

**Comment by fernandezgom** [comment]
Done, calling a service retrieves that info.

.../italk2learn/speechRecognition/speechRecoMonitor

**Comment by sergutsan** [comment]
Link to commit(s)?

**Comment by fernandezgom** [comment]
https://github.com/fernandezgom/it2l-speech-orchestration-module

**Comment by fernandezgom** [comment]
Just I checked that issue 78 includes also this issue with new details.

**Comment by sergutsan** [comment]
That is not a link to a commit. It is a link to a repo. :-P

**Comment by sergutsan** [comment]
I guess you referred to https://github.com/fernandezgom/it2l-speech-orchestration-module/commit/4304d577d1452b504f4e00b3402466fa6c0a0b23
