### ISSUE TITLE
Voice recording

### ISSUE THREAD

**Issue by sergutsan** [fernandezgom/it2l-platform#79]
The platform should be able to record the voices of users and store them: 

- connecting every 12 chunks of 5s of audio and storing 1min on disk

- naming those 1min chunks in a way that is impossible to connect to the original user, e.g. the first chunk of the day is named 20150621-user1-001.wav, and 'user1' just says that this is the first user using the system on 2015-06-21, but the user's login could be anything, from 'student1' to 'fernandezgom', and the file would still be called 20150621-user1-001.wav. The next minute for the same user would be called 20150621-user1-002.wav, etc. The first minute for another user would be called 20150621-user2-001.wav, etc. Note that if a user logs out and logs in again, the system cannot know whether they have been on the system before (because it is not the same session) to the audio minutes will then be called 20150621-user3-001.wav or something like that.

**Comment by mavrikis** [comment]
Will this approach allow someone (e.g. a researcher) with access to the
data being able to map names of chucks to users in some way that would be
secure, obscure and not accessible to random ppl? This may be needed for
analysis

**Comment by sergutsan** [comment]
In my original description, once the voice is recorded, there is no way it can be linked back to any individual user. Anonimisation all the way. 

If you think you need to map random-nicks to specific users for analysis, this can be done too but we must be careful. I would propose the following solution: the platform writes onto an encrypted file the map from the former to the latter. The password that encrypts the file is set when the server is started. 

@fernandezgom Does this make sense?

**Comment by fernandezgom** [comment]
This is done and also the transcriptions are stored too.
