### ISSUE TITLE
Fractions in task descriptions should appear properly

### ISSUE THREAD

**Issue by mavrikis** [fernandezgom/it2l-platform#84]
Sorry if there is an issue already on that. 

We have discussed it several times but never was there time to be priority. 

I don't know it is now but would be good to at least think about it as improvement. I think it is straightforward to have proper showing fractions on task descriptions. 

My proposal is the following. 

The tip files (or wherever you store the task description) could contain MathML. 
For an example look here http://www.w3.org/TR/MathML3/chapter3.html#presm.mfrac

This should be wrapped around a math element as it is supported in html5 and firefox (that is our recommended browser anyway) supports it natively. The math element can take an alttext attribute that would be the alternative if MathML is not supported e.g. the unicode or finally just that text.

To deal with the speech production requirements, in the filter for MaryTTS again the alternative could be used or some special tag to read it.

Does this make sense? 

Perhaps it is a beautification that can be done after the studies as I imagine there are other priorities.

**Comment by it2l** [comment]
This was included. Finally was easier than I thought.

**Comment by mavrikis** [comment]
Nice. Can I see it? Or want to tell me more, sorry I had to go after the other meeting so didn't get to talk to you about this.

**Comment by it2l** [comment]
Check the German platform. I uploaded there for the forthcoming studies. 
Regards, 
Jose 
El 14/8/2015 18:39, mavrikis <notifications@github.com> escribió:Nice. Can I see it? Or want to tell me more, sorry I had to go after the other meeting so didn't get to talk to you about this.
